### ISSUE TITLE
Sugar*Style Nintendo Switch data.rom doesn't extract

### ISSUE THREAD

**Issue by DSwizzy** [07th-mod/enter_extractor#1]
This tool doesn't work with the Nintendo Switch version of Sugar*Style's data.rom file, please add support for it someday if possible!

**Comment by drojf** [comment]
Please try re-downloading and running the `blabla.py` again now - olga fixed the issue where the program fails if the output folder already exists.

After you left the Discord, someone also suggested the tool here https://github.com/DCNick3/ShinDataUtil which might or might not work.

**Comment by DSwizzy** [comment]
I'll give it a try, thank you very much!

**Comment by DSwizzy** [comment]
unfortunately it gave the same error....

**Comment by drojf** [comment]
Are you sure it is the same error? I tested it just now on the Umineko rom and it works even if the output folder exists. 

I would test the data.rom for you, but isn't the data.rom huge? I'm not sure I want to download such a huge file if it's like 10GB. If there is some error other than the output folder already existing, I'm not going to be modifying the script (I don't have the skills/knowledge to do so anyway as I didn't write this script originally)

**Comment by drojf** [comment]
Also, you have Python 3 installed right? not Python 2

**Comment by drojf** [comment]
Just to be clear, the workaround would be to 

- Option 1:  delete the existing folder at `c:\temp\output`, then run the script again

- Option 2:  change the output folder like so:
```
py blabla.py data.rom c:\temp\output2
```

**Comment by drojf** [comment]
Please send a screenshot if you still have problems, so I can check what the error is.

**Comment by DSwizzy** [comment]
> Are you sure it is the same error? I tested it just now on the Umineko rom and it works even if the output folder exists.
> 
> You should be able to just specify a different folder and that would get around it too (like `c:\temp\output2`)
> 
> I would test the data.rom for you, but isn't the data.rom huge? I'm not sure I want to download such a huge file if it's like 10GB. If there is some error other than the output folder already existing, I'm not going to be modifying the script (I don't have the skills/knowledge to do so anyway as I didn't write this script originally)

Very sorry for the late reply, my email didn't notify me replying you back, my mistake! the Sugar*Style's data.rom file is about around 3.04 GB if i recalled so it's not really at all so if you want i can upload it to a google drive that way so you can check it out.

I'd didn't get around to test it just yet but i will tomorrow or around this week hopefully, will send screenshots to show any other errors if i have any other.

**Comment by DSwizzy** [comment]
> if it's that small, yea you can send the link via Discord, just join the server again and DM me

cool, alright
